env = Environment()

env['APP_TARGET'] = 'IRPaint'
env['APP_SOURCES'] = ['IRPaint.cpp', 'BlobTracker.cpp', 'ManualCalibration.cpp',
						'PParams.cpp', 'Triangle.cpp', 'Utils.cpp']
env['RESOURCES'] = ['gfx/*']
env['DEBUG'] = 1

# OpenCV
env = SConscript('../../../blocks/Cinder-OpenCV/scons/SConscript',
	exports = 'env')

SConscript('../../../scons/SConscript', exports = 'env')
